Repository Avanti-Bootcamp-GET-Geeks/back-end-plataforma-eventos-culturais, pull requests merged in 2024-05, with the labels that each got.

#21 Update README.md
  README.md
Labels: documentation

#23 3 autenticacao autorizacao
  .env.example
  index.js
  package-lock.json
  package.json
  prisma/schema.prisma
  src/auth/authorization.js
  src/controllers/EventController.js
  src/controllers/LoginController.js
  src/controllers/UserController.js
  src/middleware/validationMiddleware.js
  src/routes/eventRoutes.js
  src/routes/loginRoutes.js
Labels: enhancement

#33 32 eventos by user
  README.md
  screenshots/doc-swagger.jpg
  src/controllers/EventController.js
  src/routes/eventRoutes.js
  swagger.json
Labels: enhancement

#35 feat: add cors
  index.js
  package-lock.json
  package.json
Labels: enhancement

#36 refactor: inclusão do local completo (findAll)
  src/controllers/EventController.js
  swagger.json
Labels: refactor

#38 refactor: add campos de data e id do usuário
  src/controllers/EventController.js
  swagger.json
Labels: refactor

#40 refactor resposta events by user - /events/user/:id
  src/controllers/EventController.js
  swagger.json
Labels: refactor
